### ISSUE TITLE
React-Group-Project

### ISSUE THREAD

**Issue by everinurmind** [everinurmind/React-Group-Project#25]
[Our Kanban Board Project](https://github.com/everinurmind/React-Group-Project/projects/1)

we have 2 people on our team:
@Muhammad0602
@everinurmind

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info ✔️

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [ ] Kindly remove all cards with Team3 in the title since you are a group of two as per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md#:~:text=If%20your%20group%20includes%20two%20people%20%2D%20remove%20all%20cards%20with%20Team3%20in%20the%20title.).
- [ ] Kindly make sure that all cards on your Kanban board have assignees as per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md#:~:text=Each%20of%20the,should%20have%20assignees.). There are a couple of cards that are not assigned.
![image](https://user-images.githubusercontent.com/24703171/232592520-b2ebf9a1-1829-43bb-bfb4-ef91eced0f60.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Omar-Muhamad** [comment]
# Approved ✔
### Hi @everinurmind and @Muhammad0602,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to close this issue and start working on the project :shipit: 

### GOOD LUCK 🤞 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
